-- AlterTable
ALTER TABLE "User" ADD COLUMN "tier" TEXT NOT NULL DEFAULT 'free';
ALTER TABLE "User" ADD COLUMN "dailyChatCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "dailyCountDate" TIMESTAMP(3);
